Vagrant.configure("2") do |config|
  config.vm.box = "fedora/38-cloud-base"
  config.vm.box_version = "38.20230413.1"
  config.vm.box_url = "https://vagrantcloud.com/fedora/boxes/38-cloud-base/versions/38.20230413.1/providers/virtualbox.box"
  
  # Provider-specific configuration
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Fedora38VM"
    vb.memory = "2048"
    vb.cpus = 2
  end

  # Enable public key insertion for SSH access
  config.ssh.insert_key = true

  # Synced folder settings (optional)
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  # Network configuration (optional)
  config.vm.network "public_network", ip: "192.168.10.10"
  
  # Shell provisioner to set DNF options and update/install packages
  config.vm.provision "shell", inline: <<-SHELL
    # Set DNF to use the fastest mirror and maximum parallel downloads
    echo 'fastestmirror=True' | sudo tee -a /etc/dnf/dnf.conf
    echo 'max_parallel_downloads=10' | sudo tee -a /etc/dnf/dnf.conf

    # Update the system and install packages
    sudo dnf update -y
    sudo dnf install -y neovim podman

    mkdir -p ~/.config/nvim
    echo 'set number' >> ~/.config/nvim/init.vim
    echo 'set relativenumber' >> ~/.config/nvim/init.vim
  SHELL

end
